-- StarshipOS additive schema refresh 2026-07-07
-- Generated by refresh-gen.py: current Base44 entity schemas (169) vs migrated baseline (147 tables).
-- Idempotent: CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS. FKs documented, not enforced.

-- ===== NEW TABLES =====
-- appraisal  (entity: Appraisal)
CREATE TABLE IF NOT EXISTS "appraisal" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "name" text,
  "development_id" text,
  "development_name" text,
  "status" text,
  "as_at_date" date,
  "first_charge_name" text,
  "first_charge_amount" numeric,
  "first_charge_rate_annual" numeric,
  "first_charge_rate_monthly" numeric,
  "first_charge_interest_serviced" boolean DEFAULT false,
  "second_charge_name" text,
  "second_charge_amount" numeric,
  "second_charge_rate_monthly" numeric,
  "covenant_ltv" numeric,
  "selling_costs_pct" numeric DEFAULT 2,
  "revaluation_cost" numeric,
  "legal_cost" numeric,
  "lender_valuation" numeric,
  "land_cost" numeric,
  "construction_cost" numeric,
  "professional_fees" numeric,
  "finance_costs" numeric,
  "contingency" numeric,
  "target_profit" numeric,
  "notes" text
);
CREATE INDEX IF NOT EXISTS "idx_appraisal_development_id" ON "appraisal" ("development_id");

-- appraisal_cost_line  (entity: AppraisalCostLine)
CREATE TABLE IF NOT EXISTS "appraisal_cost_line" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "appraisal_id" text,
  "category" text,
  "description" text,
  "amount" numeric,
  "sort_order" numeric
);

-- appraisal_unit  (entity: AppraisalUnit)
CREATE TABLE IF NOT EXISTS "appraisal_unit" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "appraisal_id" text,
  "name" text,
  "unit_type" text,
  "floor" text,
  "internal_sqm" numeric,
  "internal_sqft" numeric,
  "terrace_sqm" numeric,
  "terrace_sqft" numeric,
  "asking_price" numeric,
  "price_per_sqft" numeric,
  "status" text,
  "off_charge" boolean DEFAULT false,
  "target_sale_date" date,
  "actual_sale_date" date,
  "gross_sale_price" numeric,
  "legal_costs" numeric,
  "marketing_costs" numeric,
  "other_costs" numeric,
  "net_proceeds" numeric,
  "sort_order" numeric,
  "notes" text
);

-- conviction_code  (entity: ConvictionCode)
CREATE TABLE IF NOT EXISTS "conviction_code" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "code" text,
  "description" text,
  "category" text,
  "default_points" text,
  "active" boolean DEFAULT true
);

-- driver_declaration  (entity: DriverDeclaration)
CREATE TABLE IF NOT EXISTS "driver_declaration" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "employee_id" text,
  "onboarding_id" text,
  "is_driver" boolean DEFAULT false,
  "licence_type" text,
  "licence_number" text,
  "licence_categories" jsonb DEFAULT '[]'::jsonb,
  "category_expiries" jsonb DEFAULT '{}'::jsonb,
  "test_passed_date" date,
  "issue_date" date,
  "expiry_date" date,
  "full_name_on_licence" text,
  "date_of_birth" date,
  "licence_front_url" text,
  "licence_back_url" text,
  "convictions" jsonb DEFAULT '[]'::jsonb,
  "motor_accidents" jsonb DEFAULT '[]'::jsonb,
  "has_disability" boolean,
  "disability_details" text,
  "medical_condition" boolean,
  "medical_details" text,
  "other_health" boolean,
  "other_health_details" text,
  "policy_refused" boolean,
  "policy_refused_details" text,
  "disqualified_11yr" boolean,
  "disqualified_details" text,
  "authorised_to_drive" boolean DEFAULT false,
  "certified" boolean DEFAULT false,
  "certified_by" text,
  "certified_at" timestamptz,
  "signature_url" text
);
CREATE INDEX IF NOT EXISTS "idx_driver_declaration_employee_id" ON "driver_declaration" ("employee_id");

-- email_footer_config  (entity: EmailFooterConfig)
CREATE TABLE IF NOT EXISTS "email_footer_config" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "config_key" text,
  "tagline" text,
  "website_url" text,
  "linkedin_url" text,
  "youtube_url" text,
  "sign_off_line" text,
  "footer_logo_url" text,
  "company_address" text,
  "disclaimer" text
);

-- employee_bank_details  (entity: EmployeeBankDetails)
CREATE TABLE IF NOT EXISTS "employee_bank_details" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "employee_id" text,
  "onboarding_id" text,
  "bank_name" text,
  "building_society_roll_number" text,
  "account_name" text,
  "sort_code" text,
  "account_number" text,
  "payslip_email" text,
  "payslip_password" text,
  "p45_url" text,
  "p45_name" text,
  "certified" boolean DEFAULT false,
  "certified_by" text,
  "certified_by_name" text,
  "certified_at" timestamptz,
  "signature_url" text
);
CREATE INDEX IF NOT EXISTS "idx_employee_bank_details_employee_id" ON "employee_bank_details" ("employee_id");

-- employee_compliance_review  (entity: EmployeeComplianceReview)
CREATE TABLE IF NOT EXISTS "employee_compliance_review" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "employee_id" text,
  "category" text,
  "conditions" text,
  "responsible_person_name" text,
  "responsible_person_role" text,
  "approved_by" text,
  "approved_by_name" text,
  "approved_at" timestamptz,
  "signature_url" text,
  "reviewed" boolean DEFAULT false
);
CREATE INDEX IF NOT EXISTS "idx_employee_compliance_review_employee_id" ON "employee_compliance_review" ("employee_id");

-- employee_document  (entity: EmployeeDocument)
CREATE TABLE IF NOT EXISTS "employee_document" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "employee_id" text,
  "employee_name" text,
  "document_type" text,
  "title" text,
  "file_url" text,
  "file_name" text,
  "notes" text,
  "uploaded_by" text,
  "uploaded_by_name" text,
  "document_date" date
);
CREATE INDEX IF NOT EXISTS "idx_employee_document_employee_id" ON "employee_document" ("employee_id");

-- employee_health_declaration  (entity: EmployeeHealthDeclaration)
CREATE TABLE IF NOT EXISTS "employee_health_declaration" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "employee_id" text,
  "height_feet" numeric,
  "height_inches" numeric,
  "weight_stone" numeric,
  "weight_pounds" numeric,
  "health_conditions" jsonb DEFAULT '[]'::jsonb,
  "health_questions" jsonb DEFAULT '[]'::jsonb,
  "gp_practice_name" text,
  "gp_name" text,
  "gp_address" text,
  "gp_phone" text,
  "criminal_unspent" boolean,
  "criminal_imprisoned_2yr" boolean,
  "criminal_under_investigation" boolean,
  "criminal_details" text,
  "additional_info" text,
  "certified" boolean DEFAULT false,
  "certified_by" text,
  "certified_by_name" text,
  "certified_at" timestamptz,
  "signature_url" text
);
CREATE INDEX IF NOT EXISTS "idx_employee_health_declaration_employee_id" ON "employee_health_declaration" ("employee_id");

-- handbook_declaration  (entity: HandbookDeclaration)
CREATE TABLE IF NOT EXISTS "handbook_declaration" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "employee_id" text,
  "employee_name" text,
  "employee_email" text,
  "section_id" text,
  "signature_url" text,
  "signed_date" timestamptz,
  "ip_address" text,
  "device_type" text
);
CREATE INDEX IF NOT EXISTS "idx_handbook_declaration_employee_id" ON "handbook_declaration" ("employee_id");

-- handbook_section  (entity: HandbookSection)
CREATE TABLE IF NOT EXISTS "handbook_section" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "section_number" numeric,
  "icon" text,
  "title" text,
  "summary" text,
  "body_html" text,
  "is_published" boolean DEFAULT true
);

-- incident_report  (entity: IncidentReport)
CREATE TABLE IF NOT EXISTS "incident_report" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "report_type" text,
  "reference" text,
  "development_id" text,
  "development_name" text,
  "reported_by" text,
  "reported_by_name" text,
  "report_date" date,
  "report_time" text,
  "location" text,
  "post_code" text,
  "brief_details" text,
  "people_present" jsonb DEFAULT '[]'::jsonb,
  "injured_persons" jsonb DEFAULT '[]'::jsonb,
  "first_aider_name" text,
  "first_aider_signature_url" text,
  "witnesses" jsonb DEFAULT '[]'::jsonb,
  "damaged_property" jsonb DEFAULT '[]'::jsonb,
  "damage_reported_to_manager" boolean,
  "damage_manager_details" text,
  "equipment_taken_off_operations" boolean,
  "defective_asset_id" text,
  "defective_asset_number" text,
  "immediate_actions" jsonb DEFAULT '[]'::jsonb,
  "hs_representative_notified_name" text,
  "hs_representative_notified_date" date,
  "recorded_in_accident_book" boolean,
  "accident_book_location" text,
  "investigation_person_name" text,
  "investigation_person_position" text,
  "investigation_person_location" text,
  "investigation_person_contact" text,
  "report_completed_by_name" text,
  "report_completed_signature_url" text,
  "report_completed_date" date,
  "reported_to_hse" boolean,
  "hse_report_date" date,
  "hse_report_time" text,
  "hse_reference" text,
  "inspector_name" text,
  "inspection_date" date,
  "inspection_time" text,
  "hse_notices" jsonb DEFAULT '[]'::jsonb,
  "corrective_actions" jsonb DEFAULT '[]'::jsonb,
  "hse_correspondence" jsonb DEFAULT '[]'::jsonb,
  "our_response_files" jsonb DEFAULT '[]'::jsonb,
  "line_management_prevention_actions" text,
  "line_management_breach_actions" text,
  "line_management_completed_by" text,
  "line_management_position" text,
  "line_management_date" date,
  "status" text,
  "closed_by" text,
  "closed_by_name" text,
  "closed_date" timestamptz,
  "close_out_actions" text,
  "close_out_evidence_url" text,
  "close_out_evidence_name" text
);
CREATE INDEX IF NOT EXISTS "idx_incident_report_development_id" ON "incident_report" ("development_id");

-- j5_check_item  (entity: J5CheckItem)
CREATE TABLE IF NOT EXISTS "j5_check_item" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "phase" text,
  "question" text,
  "sort_order" numeric,
  "is_active" boolean DEFAULT true,
  "photo_required" boolean DEFAULT false
);

-- j5_check_response  (entity: J5CheckResponse)
CREATE TABLE IF NOT EXISTS "j5_check_response" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "manufacturing_job_id" text,
  "phase" text,
  "check_item_id" text,
  "question" text,
  "checked" boolean DEFAULT false,
  "checked_by" text,
  "checked_at" text,
  "photo_url" text,
  "photo_upload_token" text,
  "photo_uploaded_at" text
);

-- onboarding_record  (entity: OnboardingRecord)
CREATE TABLE IF NOT EXISTS "onboarding_record" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "employee_id" text,
  "worker_type" text,
  "status" text,
  "is_driver" boolean DEFAULT false,
  "stage_progress" jsonb DEFAULT '{}'::jsonb,
  "line_manager_id" text,
  "line_manager_name" text,
  "line_manager_certified" boolean DEFAULT false,
  "line_manager_certified_at" timestamptz,
  "line_manager_signature_url" text,
  "invited_at" timestamptz,
  "notes" text,
  "completed" boolean DEFAULT false,
  "completed_at" timestamptz,
  "completed_by" text,
  "completed_by_name" text,
  "completed_by_signature_url" text,
  "onboarding_snapshot" jsonb DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS "idx_onboarding_record_employee_id" ON "onboarding_record" ("employee_id");

-- ppe_asset_issue  (entity: PPEAssetIssue)
CREATE TABLE IF NOT EXISTS "ppe_asset_issue" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "employee_id" text,
  "employee_name" text,
  "issue_type" text,
  "asset_id" text,
  "item_name" text,
  "size" text,
  "quantity" numeric DEFAULT 1,
  "issued_date" date,
  "issued_by" text,
  "issued_by_name" text,
  "signed_for" boolean DEFAULT false,
  "signature_url" text,
  "signed_at" timestamptz,
  "returned" boolean DEFAULT false,
  "returned_date" date,
  "notes" text
);
CREATE INDEX IF NOT EXISTS "idx_ppe_asset_issue_employee_id" ON "ppe_asset_issue" ("employee_id");

-- right_to_work_check  (entity: RightToWorkCheck)
CREATE TABLE IF NOT EXISTS "right_to_work_check" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "employee_id" text,
  "onboarding_id" text,
  "nationality" text,
  "immigration_status" text,
  "share_code" text,
  "rtw_expiry_date" date,
  "rtw_followup_date" date,
  "british_irish_route" text,
  "date_of_birth" date,
  "documents" jsonb DEFAULT '[]'::jsonb,
  "id_checklist" jsonb DEFAULT '{}'::jsonb,
  "status" text,
  "verified_by" text,
  "verified_by_name" text,
  "verified_at" timestamptz,
  "verified_signature_url" text,
  "certified_by" text,
  "certified_by_name" text,
  "certified_at" timestamptz,
  "certified_signature_url" text
);
CREATE INDEX IF NOT EXISTS "idx_right_to_work_check_employee_id" ON "right_to_work_check" ("employee_id");

-- sales_presentation  (entity: SalesPresentation)
CREATE TABLE IF NOT EXISTS "sales_presentation" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "title" text,
  "category" text,
  "description" text,
  "presentation_content_url" text,
  "presentation_content_name" text,
  "doc_files" jsonb DEFAULT '[]'::jsonb,
  "doc_links" jsonb DEFAULT '[]'::jsonb,
  "is_active" boolean DEFAULT true,
  "sort_order" numeric DEFAULT 0
);

-- toolbox_talk  (entity: ToolboxTalk)
CREATE TABLE IF NOT EXISTS "toolbox_talk" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "code" text,
  "title" text,
  "summary" text,
  "document_url" text,
  "document_name" text,
  "issued_date" date,
  "issued_by" text,
  "category" text,
  "mandatory_for_everyone" boolean DEFAULT false,
  "mandatory_development_ids" jsonb DEFAULT '[]'::jsonb,
  "requires_signature" boolean DEFAULT true,
  "is_active" boolean DEFAULT true
);

-- toolbox_talk_signoff  (entity: ToolboxTalkSignoff)
CREATE TABLE IF NOT EXISTS "toolbox_talk_signoff" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "toolbox_talk_id" text,
  "toolbox_talk_code" text,
  "toolbox_talk_title" text,
  "employee_id" text,
  "employee_name" text,
  "development_id" text,
  "development_name" text,
  "read_at" timestamptz,
  "read_confirmed" boolean DEFAULT false,
  "signed_by_user_email" text,
  "signed_at" timestamptz,
  "signature_url" text,
  "declaration_accepted" boolean DEFAULT false,
  "training_record_id" text
);
CREATE INDEX IF NOT EXISTS "idx_toolbox_talk_signoff_development_id" ON "toolbox_talk_signoff" ("development_id");
CREATE INDEX IF NOT EXISTS "idx_toolbox_talk_signoff_employee_id" ON "toolbox_talk_signoff" ("employee_id");

-- user_access_audit  (entity: UserAccessAudit)
CREATE TABLE IF NOT EXISTS "user_access_audit" (
  "id" text PRIMARY KEY,
  "created_date" timestamptz,
  "updated_date" timestamptz,
  "created_by" text,
  "created_by_id" text,
  "is_sample" boolean DEFAULT false,
  "target_user_id" text,
  "target_user_email" text,
  "target_user_name" text,
  "linked_employee_id" text,
  "change_summary" text,
  "changed_field" text,
  "old_value" text,
  "new_value" text,
  "changed_by_id" text,
  "changed_by_email" text,
  "changed_by_name" text,
  "source" text,
  "changed_at" timestamptz
);

-- ===== NEW COLUMNS ON EXISTING TABLES =====
-- app_config
ALTER TABLE "app_config" ADD COLUMN IF NOT EXISTS "crane_wind_limit_ms" numeric;
ALTER TABLE "app_config" ADD COLUMN IF NOT EXISTS "crane_wind_warning_tolerance_ms" numeric;

-- check_response
ALTER TABLE "check_response" ADD COLUMN IF NOT EXISTS "development_id" text;
ALTER TABLE "check_response" ADD COLUMN IF NOT EXISTS "development_name" text;

-- credit_note
ALTER TABLE "credit_note" ADD COLUMN IF NOT EXISTS "hired_asset_id" text;
ALTER TABLE "credit_note" ADD COLUMN IF NOT EXISTS "hire_reference" text;

-- employee
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "telephone" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "mobile" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "house_no" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "address_line" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "town_city" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "county" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "post_code" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "company_email" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "marital_status" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "ethnicity" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "emergency_contact_name" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "emergency_contact_address" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "emergency_contact_telephone" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "emergency_contact_mobile" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "emergency_contact_relationship" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "worker_type" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "continuous_service_date" date;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "development_code" text;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "annual_leave_entitlement" numeric;
ALTER TABLE "employee" ADD COLUMN IF NOT EXISTS "sick_leave_entitlement" numeric;

-- gsd_action
ALTER TABLE "gsd_action" ADD COLUMN IF NOT EXISTS "assigned_to_employee_id" text;
ALTER TABLE "gsd_action" ADD COLUMN IF NOT EXISTS "assigned_to_name" text;

-- gsd_action_log
ALTER TABLE "gsd_action_log" ADD COLUMN IF NOT EXISTS "log_type" text;

-- gsd_log
ALTER TABLE "gsd_log" ADD COLUMN IF NOT EXISTS "assigned_to_employee_id" text;
ALTER TABLE "gsd_log" ADD COLUMN IF NOT EXISTS "assigned_to_name" text;
ALTER TABLE "gsd_log" ADD COLUMN IF NOT EXISTS "source_incident_report_id" text;
ALTER TABLE "gsd_log" ADD COLUMN IF NOT EXISTS "source_corrective_action_index" numeric;

-- hired_asset
ALTER TABLE "hired_asset" ADD COLUMN IF NOT EXISTS "cost_line_items" jsonb DEFAULT '[]'::jsonb;

-- invitation
ALTER TABLE "invitation" ADD COLUMN IF NOT EXISTS "employee_id" text;

-- po_audit_log
ALTER TABLE "po_audit_log" ADD COLUMN IF NOT EXISTS "cvr_previous_category_type" text;
ALTER TABLE "po_audit_log" ADD COLUMN IF NOT EXISTS "cvr_previous_category_name" text;
ALTER TABLE "po_audit_log" ADD COLUMN IF NOT EXISTS "cvr_previous_period" text;
ALTER TABLE "po_audit_log" ADD COLUMN IF NOT EXISTS "cvr_new_category_type" text;
ALTER TABLE "po_audit_log" ADD COLUMN IF NOT EXISTS "cvr_new_category_name" text;
ALTER TABLE "po_audit_log" ADD COLUMN IF NOT EXISTS "cvr_new_period" text;

-- training_module
ALTER TABLE "training_module" ADD COLUMN IF NOT EXISTS "module_type" text;
ALTER TABLE "training_module" ADD COLUMN IF NOT EXISTS "self_certify" boolean DEFAULT true;
ALTER TABLE "training_module" ADD COLUMN IF NOT EXISTS "mandatory_for_everyone" boolean DEFAULT false;
ALTER TABLE "training_module" ADD COLUMN IF NOT EXISTS "mandatory_scope" text;
ALTER TABLE "training_module" ADD COLUMN IF NOT EXISTS "mandatory_development_ids" jsonb DEFAULT '[]'::jsonb;
ALTER TABLE "training_module" ADD COLUMN IF NOT EXISTS "mandatory_employee_ids" jsonb DEFAULT '[]'::jsonb;
ALTER TABLE "training_module" ADD COLUMN IF NOT EXISTS "doc_links" jsonb DEFAULT '[]'::jsonb;
ALTER TABLE "training_module" ADD COLUMN IF NOT EXISTS "doc_files" jsonb DEFAULT '[]'::jsonb;
ALTER TABLE "training_module" ADD COLUMN IF NOT EXISTS "training_content_url" text;
ALTER TABLE "training_module" ADD COLUMN IF NOT EXISTS "training_content_name" text;
ALTER TABLE "training_module" ADD COLUMN IF NOT EXISTS "training_content_updated" timestamptz;
ALTER TABLE "training_module" ADD COLUMN IF NOT EXISTS "issue_date" date;
ALTER TABLE "training_module" ADD COLUMN IF NOT EXISTS "issued_by_name" text;
ALTER TABLE "training_module" ADD COLUMN IF NOT EXISTS "tbt_pdf_url" text;
ALTER TABLE "training_module" ADD COLUMN IF NOT EXISTS "tbt_pdf_name" text;

-- training_record
ALTER TABLE "training_record" ADD COLUMN IF NOT EXISTS "employee_email" text;
ALTER TABLE "training_record" ADD COLUMN IF NOT EXISTS "completed_date" date;
ALTER TABLE "training_record" ADD COLUMN IF NOT EXISTS "user_id" text;

-- user
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "employee_id" text;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "is_finance" boolean DEFAULT false;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "is_commercial" boolean DEFAULT false;
